[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[package]
name = "perceive_semantix_lib"
version = "0.0.2"

[package.build]
backend = { name = "pixi-build-python", version = "*" }

[package.host-dependencies]
hatchling = "*"

[package.run-dependencies]
ultralytics = "*"
open-clip-torch = "*"
jaxtyping = "*"
supervision = "*"
typeguard = "2.*" # apparently version 3.* and 4.* have some issues for jaxtyping
rerun-sdk = "==0.34.1"
openai = "*"
joblib = "*"
py-opencv = "*"
